name: Docker Image CI (build, python dependencies test, push registry)
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths-ignore:
      -  "*.md"
  pull_request:
    branches: 
      - "main"
    paths-ignore:
      - "*.md"
       
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone Repository
      uses: actions/checkout@v4

    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        
    - name: Install Dependencies
      run: |
        python -m pip install -r requirements.txt

#    - name: Get refs - this will be used as tags later on
#      shell: bash
#      run: |
#        echo "::set-output name=sha12::$(echo ${GITHUB_SHA} | cut -c1-12)"
#      id: getrefs

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Docker meta
      id: meta # you'll use this in the next step
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: |
          f1d094/alarmdecoder-mqtt
        # Docker tags based on the following events/attributes
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: "."
        file: "Dockerfile"
        platforms: linux/arm64v8,linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        
#    - name: Push
#      if: github.ref == 'refs/heads/main'
#      uses: docker/build-push-action@v2
#      with:
#        context: "."
#        file: "Dockerfile"
#        push: true
#        tags: |
#          f1d094/alarmdecoder-mqtt:${{steps.getrefs.outputs.sha12}}, f1d094/alarmdecoder-mqtt:latest
